version: '3'
services:
  frontend:
    build:
      context: ../personal-website-fe
      dockerfile: Dockerfile
      # target: development
    ports:
      - "3000:3000"
    depends_on:
      - backend
    volumes:
      - ../personal-website-fe:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
      - VITE_BACKEND_API=http://localhost/api/

  backend:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DATABASE_HOST=db
      - DATABASE_PORT=5432
      - DATABASE_USER=myuser
      - DATABASE_PASSWORD=mypassword
      - DATABASE_NAME=mydb
      - DATABASE_SSLMODE=disable
      - SERVER_PORT=8000

  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword
      - POSTGRES_DB=mydb

  nginx:
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf.template
      - ./go.sh:/go.sh
    depends_on:
      - frontend
      - backend
    command: ["/bin/sh", "-c", "chmod +x /go.sh && /go.sh"]
    environment:
      - FRONTEND_SERVER=frontend:3000
      - BACKEND_SERVER=backend:8000
  

volumes:
  postgres_data: